/**
 * Typed access to the build output of scripts/build-data.ts.
 * The JSON files are git-ignored and regenerated by `npm run build:data` (also run by predev/prebuild/precheck).
 */
import type { Building, Store } from './schema'
import buildingsJson from '../generated/buildings.json'
import storesJson from '../generated/stores.json'

export const stores: readonly Store[] = storesJson as unknown as Store[]
export const buildings: readonly Building[] = buildingsJson as unknown as Building[]
